name: Azure Pages CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  azure_pages_job:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
    - uses: actions/checkout@v1
    - name: Build And Deploy
      id: azurepagesbuilddeploy
      uses: joslinmicrosoft/basic-deploy-task@master
      with:
        azure_pages_buildhost: 'buildsystem2.azurewebsites.net'
        azure_pages_api_token: ${{ secrets.AZURE_PAGES_API_TOKEN }}        
        azure_pages_api_version: 'v1' # optional        
        app_build_output_location: 'build'
        app_source_location: 'app' # optional
        azure_function_location: 'api' # optional
